---
- name: install apache & php & mysql
  hosts: host2
  become: true
  become_user: root
  gather_facts: true
  tasks:
    #    - name: "Update apt-get repo and cache"
    #  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: "Install appache2"
      package: name=apache2 state=present
    - name: "install appache2-php5"
      package: name=libapache2-mod-php state=present
    - name: "install php-cli"
      package: name=php-cli state=present
    - name: "Install php-mcrypt"
      package: name=php-mcrypt state=latest
    - name: "install php-gd"
      package: name=php-gd state=present
    - name: "install php-mysql"
      package: name=php-mysql state=present
    - name: "install mysqlserver"
      package: name=mysql-server state=present
